---
- name: Download Composer Installation Script
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php

- name: Run Composer Installer
  command:
    cmd: /usr/bin/php /tmp/composer-setup.php
    creates: composer.phar

- name: Copy Composer Executable to /usr/local/bin
  become: true
  copy:
    src: composer.phar
    dest: /usr/local/bin/composer
    remote_src: yes
    mode: '0777'

- name: Remove phar
  become: true
  file:
    path: composer.phar
    state: absent