---
- name: System Update & Upgrade
  apt:
    update_cache: true
    upgrade: dist
    force_apt_get: true
  
- name: Install Apache2, MariaDB, Git, Python Modules, GPG, UFW
  apt:
    name:
      - apache2
      - mariadb-server
      - mariadb-client
      - git
      - python3
      - python3-pip
      - gpg
      - ufw
    state: present
    update_cache: true

- name: Install PyMySQL
  pip:
    name:
      - PyMySQL

      
- name: Start & Enable MariaDB Service
  service:
    name: mysql
    state: started
    enabled: true

- name: Start & Enable Apache2 Service
  service:
    name: apache2
    state: started
    enabled: true

- name: Install PHP Packages
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - software-properties-common
    state: present

- name: Add GPG Repository Key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add PHP Repository
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
    filename: sury-php
    update_cache: true
  
- name: Update Repository
  apt:
    update_cache: true

- name: Install PHP 8.1
  apt:
    name:
      - php8.1
      - libapache2-mod-php
      - php8.1-dev
      - php8.1-zip
      - php8.1-curl
      - php8.1-mbstring
      - php8.1-mysql
      - php8.1-gd
      - php8.1-xml
    state: present

- name: Create App Database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create App Database User with Full Access to Database
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_passwd }}"
    priv: 'laravel_realworld_app_db.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: true


- name: UFW - Allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH

- name: UFW - Allow SSH on port 22
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: UFW - Allow HTTP on port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: UFW - Allow HTTPS on port 443
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: UFW - Allow WWW Full
  ufw:
    rule: allow
    name: 'WWW Full'

- name: Enable UFW
  ufw:
    state: enabled